# Generated by Django 6.1 on 2026-09-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcommand',
            name='added_automatically',
            field=models.BooleanField(default=False),
        ),
    ]
