# Generated by Django 6.1 on 2026-09-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appcommand_added_automatically'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcommand',
            name='category',
            field=models.CharField(choices=[('browser', 'Браузер'), ('messenger', 'Месенджер'), ('game', 'Гра'), ('media', 'Медіа/музика/відео'), ('utility', 'Стандартна програма/утиліта'), ('dev_tool', 'Інструмент розробника'), ('other', 'Інше')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='appcommand',
            name='keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
